apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
  namespace: np-deepdive-one
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: ClusterIP
---
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: web
  namespace: np-deepdive-one
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: web
    ports:
    - containerPort: 80
      protocol: TCP
    command: [nginx-debug, '-g', 'daemon off;']

